zc/permantLabLimit
ius-csg/cslabs-backend pull request #35
Opened 2021-07-19 05:24 UTC by Cliftonz

2021-07-28 05:47 UTC, jasekiw commented
@Cliftonz What is `PermanentLabLimit` refering to? Which task in trello does this link to?

2021-07-28 05:53 UTC, Cliftonz commented
I do not know why I did not fill out the description. This change is to set a default amount of permanent labs a creator can make to 1. This way they can not add a bunch of permanent labs that never get spun down and hog our resources.

2021-07-28 05:55 UTC, Cliftonz commented
https://trello.com/c/ho4ZFZm1/482-creators-should-have-a-limit-on-how-many-permanent-labs-they-can-have

2021-07-29 23:24 UTC, jasekiw requested changes
This seems more like a frontend and controller level task. I don't think it's ready for a PR to merge yet.

2021-07-29 23:24 UTC, jasekiw commented on CSLabs.Api/Models/UserModels/User.cs
> +        [Required] private int AmountOfPermanentLabs {get; set;}
This can be calculated on the fly with little effort. No need to store it.

2021-07-29 23:24 UTC, jasekiw commented on CSLabs.Api/Models/UserModels/User.cs
> +        [Required] private int PermanentLabLimit { get; set; }
Are we wanting to adjust the permanent lab limit on a per user basis?

2021-08-10 23:46 UTC, jasekiw commented
@Cliftonz please change base branch to dev, not master

2021-09-07 15:37 UTC, jasekiw commented on CSLabs.Api/Models/UserModels/User.cs
> +        [Required] private int PermanentLabLimit { get; set; }
I think you answered this in the meeting and the answer was yes.

2021-09-07 15:38 UTC, jasekiw commented on CSLabs.Api/Migrations/20210809190958_PermanentLabLimit.cs
> +
Where's the migration code? The `migrations add` command should have generated the statements for you.

2021-09-07 15:42 UTC, jasekiw commented
Converted this PR to a draft until the migrations are properly added, and the variable is used by the backend to prevent users from creating more than the permanent limit.

2021-11-04 03:36 UTC, jasekiw commented
I'm closing this since no activity has occurred in a while. Once it is ready for review, you can re-open it.

2021-11-04 03:36 UTC, closed without merging