Banner
ius-csg/cslabs-backend pull request #41
Opened 2021-09-03 14:46 UTC by AStiner

Jason here is the request you asked for.

2021-09-07 16:06 UTC, jasekiw requested changes
Once you address the requested changes, your next steps will be (in any order for this situation)

Create a controller that will return the active alerts.
Create a database migration using the `dotnet ef migrations add` command - use the microsoft docs to understand how to do this. https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/?tabs=dotnet-core-cli#evolving-your-model

I also have a section written specifically for this project: https://github.com/ius-csg/cslabs-backend/blob/81043cc176fb9f7080c4819f3985b2d1523992a3/README.md#ef-core

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +        public string timestamp { get; set; }
All Property names need to follow `PascalCase`, the names always start with a capital letter.

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +    public class Banner : Trackable
I would rename this to `Alert` to keep the naming in line with the frontend. As a general rule of thumb, try to stick with the name that is already created in order to reduce confusion and learning curve of the codebase.

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +        [Column(TypeName = "TEXT")]//need to decide on a enum
Create an enum called `EAlertType`, add the different options. You must add an annotation to allow it to be serialized into test when sent in a response to the frontend: `[JsonConverter(typeof(StringEnumConverter))]`

Here is an example of a model that has it's own enum for it's type: https://github.com/ius-csg/cslabs-backend/blob/81043cc176fb9f7080c4819f3985b2d1523992a3/CSLabs.Api/Models/ModuleModels/Lab.cs#L24-L26


You also need to tell entity framework to map it as a string to the database. You can do this by creating a static method call OnModelCreating in the Alert (Banner) class.

Here is an example from the lab class:

https://github.com/ius-csg/cslabs-backend/blob/81043cc176fb9f7080c4819f3985b2d1523992a3/CSLabs.Api/Models/ModuleModels/Lab.cs#L120
in the OnModelCreating  for the Lab:
https://github.com/ius-csg/cslabs-backend/blob/81043cc176fb9f7080c4819f3985b2d1523992a3/CSLabs.Api/Models/ModuleModels/Lab.cs#L116-L121

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +        public string timestamp { get; set; }
If this is a timestamp make the type a `DateTime` object instead of a string.

Is this timestamp the start or the end of when the alert should show? I would imagine you would need both a start and an end. @Cliftonz Can you confirm this?

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Enums/EBannerTypes.cs
> +    public enum EBannerTypes
rename to `EBannerType`.  As a general rule of thumb, classes and enums should be singular (not plural).

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +            builder.Unique<Banner>(u => u.EBannerTypes);
You probably don't want this to be unique, that would mean there could only be one alert of each type in the database. That doesn't sound right.

2021-09-07 16:06 UTC, jasekiw commented on CSLabs.Api/Models/Banner.cs
> +        public string Description { get; set; }
I would rename this to `Message` since we are going with `Alert` terminology.

2021-09-16 22:08 UTC, AStiner commented
Can I just delete the file of the migration that I accidentally created?

2021-09-17 13:35 UTC, jasekiw requested changes
@AStiner 

No, you cannot remove it manually. You have to use the command to revert the migraton first:  `dotnet ef database update <insert the last migration name before the one you want to remove>`.

Then use `dotnet ef migrations remove` to remove it completely. 

The management of the migrations must be done with the command otherwise we risk corrupting or database snapshot.

Now on to the other issue I saw: your migrations are not doing anything - notice your up and down methods are blank. Go ahead and revert both these migrations using the instructions above iteratively.

The documentation might have not mentioned this part:

You must add the system message class as a DbSet property to the `DefaultContext` class otherwise the generated migration won't pick up the new model.

Add it right behind the `HypervisorVmTemplates` property.
```
 public DbSet<HypervisorVmTemplate> HypervisorVmTemplates { get; set; }
 public DbSet<SystemMessage> SystemMessages { get; set; }
```

Then Rename `SystemMessage.OnAlertCreation` to `SystemMessage.OnModelCreating` to match convention and call it in the `DefaultContext.OnModelCreating`.

Make system message implement `IPrimaryKeyModel` as well.

2021-09-21 04:31 UTC, jasekiw requested changes

2021-09-21 04:31 UTC, jasekiw commented on CSLabs.Api/Controllers/SystemMessagesController.cs
> +            public async Task<IActionResult> GetSystemMessageID(int id)
I'm not sure we're ever going to need to directly get a single message, for the most part we will get all the messages for our timeframe or all the messages to show in a list.

2021-09-21 04:31 UTC, jasekiw commented on CSLabs.Api/Controllers/SystemMessagesController.cs
> +            public async Task<IActionResult> UpsertSystemMessage()
Upsert stands for update or insert. So either have an upsert method or an update and create method but not both. (you have both upsert and UpdateSystemMessage methods)

2021-09-21 05:05 UTC, jasekiw commented
Also: The controllers by convention are singular not plural.

2021-09-23 22:50 UTC, jasekiw commented on CSLabs.Api/CSLabs.Api.csproj
> +    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.5" />
What are these changes for? We're not using any of these packages. There's a small chance this change is why you're having problems with the registration.

2021-09-24 04:44 UTC, jasekiw reviewed
This PR is looking pretty good! Once you test it with the frontend and thing seem like they're working, I'm good to merge it assuming I don't find anything else. Good job!

2021-10-06 01:32 UTC, closed without merging