Jh/disable module
ius-csg/cslabs-backend pull request #42
Opened 2021-09-21 01:41 UTC by jhurst502

2021-09-21 01:43 UTC, Cliftonz commented
This pr should go to dev instead of master.
Also, it only looks like you changed one thing so I belive this should be a draft pr untill the whole feature is done.

2021-09-21 04:32 UTC, jasekiw commented
I agree, this PR is missing the migration for this property. Also adding the required attribute without adjusting the frontend to pass this attribute will break our ability to edit modules.

2021-09-24 04:39 UTC, jasekiw requested changes, later dismissed
We need to deny requests to the UserModuleController to prevent people from being able to create a new instance of a module even if the UI denies them since the UI can always be bypassed by a hacker.

2021-10-23 16:33 UTC, Cliftonz commented on CSLabs.Api/Controllers/UserLabController.cs
> +                    return Ok(userLab.GetResponse(Mapper));
You should only have one return in a function.

2021-10-23 16:34 UTC, Cliftonz submitted a review, later dismissed
LGTM other then the two return statements

2021-10-23 20:45 UTC, jhurst502 commented on CSLabs.Api/Controllers/UserLabController.cs
> +                    return Ok(userLab.GetResponse(Mapper));
I think in this case multiple returns would be fine, only one thing is being returned depending on the data. This is how we do it in the other controllers as well, and how its done according to the docs for entity framework
![image](https://user-images.githubusercontent.com/68161572/138570960-8b7d7eb2-2964-41ed-b1b8-ddda894f52d3.png)

2021-11-03 01:04 UTC, jasekiw requested changes

2021-11-03 01:04 UTC, jasekiw commented on CSLabs.Api/Controllers/UserLabController.cs
> +                    select module.Disabled;
Please use lamda version of LINQ to match the rest of the queries in the codebase.

2021-11-03 01:04 UTC, jasekiw commented on CSLabs.Api/Controllers/UserLabController.cs
> +                    return Ok(userLab.GetResponse(Mapper));
Multiple returns is fine

2021-11-03 01:04 UTC, jasekiw commented on CSLabs.Api/Controllers/UserLabController.cs
> +                    select module.Disabled;
Try the following:

```suggestion
            var isDisabled = await DatabaseContext.Modules
                .Where(m => m.Labs.Any(l => l.UserLabs.Any(ul => ul.Id == id)))
                .Select(m => m.Disabled)
                .FirstAsync();
```

2021-11-03 01:04 UTC, jasekiw commented on CSLabs.Api/Controllers/UserLabController.cs
> +                return BadRequest(new {Message = "Lab is currently disabled"});
I would invert this if statement to reduce nesting.

```suggestion
            if (isDisabled)
            {
                return BadRequest(new {Message = "Lab is currently disabled"});
            }
            var userLab = await DatabaseContext.UserLabs
                .IncludeRelations()
                .IncludeLabHypervisor()
                .Include(ul => ul.Lab)
                .FirstAsync(ul => ul.Id == id);
            if (userLab.UserLabVms.Count > 0) // update the UI.
                return Ok(userLab);
            await _instantiationService.Instantiate(userLab, ProxmoxManager);
            await DatabaseContext.SaveChangesAsync();
            return Ok(userLab.GetResponse(Mapper));
```

2021-11-03 13:44 UTC, jasekiw commented
@jhurst502 You did not follow the instructions properly for handling your migration, you now have two migrations, one that does something, and one that does not.

2021-11-03 13:45 UTC, jasekiw commented
@jhurst502 You forgot the remove migration step one the second merge.
![image](https://user-images.githubusercontent.com/4037224/140071417-88a72916-d3d0-414e-a5be-19cd56df8dfd.png)

2021-11-04 03:24 UTC, merged